// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1gS4vVvvJ3t4KQiGiP31AU1or4kL4qdA',
    appId: '1:922447048114:web:889f810bfaff77a62388ab',
    messagingSenderId: '922447048114',
    projectId: 'silentsignalai-87900',
    authDomain: 'silentsignalai-87900.firebaseapp.com',
    storageBucket: 'silentsignalai-87900.firebasestorage.app',
    measurementId: 'G-SBL86JK8X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9eOhAsZqw8pZVuitlE6YNmTgk39uSHQ',
    appId: '1:922447048114:android:7ee1a2bd1c95c9322388ab',
    messagingSenderId: '922447048114',
    projectId: 'silentsignalai-87900',
    storageBucket: 'silentsignalai-87900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzc4SabhhluWdbb9W8-91Yt3UF8gv7JTs',
    appId: '1:922447048114:ios:02a49cfbd6ad59172388ab',
    messagingSenderId: '922447048114',
    projectId: 'silentsignalai-87900',
    storageBucket: 'silentsignalai-87900.firebasestorage.app',
    iosBundleId: 'com.example.silentSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzc4SabhhluWdbb9W8-91Yt3UF8gv7JTs',
    appId: '1:922447048114:ios:02a49cfbd6ad59172388ab',
    messagingSenderId: '922447048114',
    projectId: 'silentsignalai-87900',
    storageBucket: 'silentsignalai-87900.firebasestorage.app',
    iosBundleId: 'com.example.silentSignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1gS4vVvvJ3t4KQiGiP31AU1or4kL4qdA',
    appId: '1:922447048114:web:d0415630ace310692388ab',
    messagingSenderId: '922447048114',
    projectId: 'silentsignalai-87900',
    authDomain: 'silentsignalai-87900.firebaseapp.com',
    storageBucket: 'silentsignalai-87900.firebasestorage.app',
    measurementId: 'G-CKMZ24SB6R',
  );

}